import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contato",
  description: "Generated by create next app",
};

const Contact = () => {
  return (
    <div>
      <h1>Contato</h1>
    </div>
  );
};

export default Contact;
