name: CI/CD Pipeline

on:
  push:
    tags:
      - '*'

jobs:
  Docker-Image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t lucasamaraldev .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: docker tag lucasamaraldev lucassamaral/lucasamaraldev:${{github.ref}} && docker push lucassamaral/lucasamaraldev:${{github.ref}}

  Deploy-Production:
    needs: Docker-Image
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH into EC2 and Pull Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: docker pull lucassamaral/lucasamaraldev:${{github.ref}} && docker stop lucasamaraldev && docker rm lucasamaraldev && docker run -d -p 80:3000 --name lucasamaraldev lucassamaral/lucasamaraldev:${{github.ref}}
